global:
  resolve_timeout: 5m

route:
  receiver: 'slack_notifications'

receivers:
  - name: 'slack_notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX'
        channel: '#alerts'
        text: "{{ .CommonAnnotations.summary }}\n\nDetails:\n{{ range .Alerts }}• {{ .Annotations.description }}\n{{ end }}"
