global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email_notification'
receivers:
  - name: 'email_notification'
    email_configs:
    - to: #Email_Whom_you_want_to_share_alerts_with
      from: test@gmail.com
      smarthost: smtp.gmail.com:587   #SMTP_SERVER_MAIL
      auth_username: test@gmail.com
      auth_identity: test@gmail.com
      auth_password: #your_Google_generated_APP_Password
      send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
